language: java

branches:
  only:
    - master
    - /^release.*$/ 

jdk:
  - oraclejdk8

before_script:
  - cd src/lib/kotlin
  - chmod +x gradlew
  - chmod +x gradle/wrapper/gradle-wrapper.jar

script:
  - ./gradlew test build